# Generated by Django 4.1.5 on 2023-04-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realapp', '0002_productdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='Image',
            field=models.ImageField(null=True, upload_to='Profile'),
        ),
    ]
